# Generated by Django 5.2.10 on 2026-01-27 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Voice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="표시 이름")),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="API 코드"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("N", "Neutral")],
                        max_length=10,
                        verbose_name="성별",
                    ),
                ),
                ("description", models.TextField(verbose_name="목소리 설명")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="사용 가능 여부"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TTSGeneration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="입력 텍스트")),
                ("speed", models.FloatField(default=1.0, verbose_name="속도")),
                (
                    "audio_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="tts/",
                        verbose_name="생성된 오디오 파일",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "대기중"),
                            ("PROCESSING", "생성중"),
                            ("COMPLETED", "완료"),
                            ("FAILED", "실패"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="진행 상태",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="요청자",
                    ),
                ),
                (
                    "voice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.voice",
                        verbose_name="선택 목소리",
                    ),
                ),
            ],
        ),
    ]
