"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-qxhsrtrf2(i&o%gjzx48(265n9+am8qy)71m*t=c&=386(3c0m"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'rest_framework',
    'rest_framework.authtoken', # 
    'rest_framework_simplejwt', # 토큰 관리
    'api',
    # ★ 로그인용 추가
    'dj_rest_auth',             # 로그인/로그아웃 API
    'django.contrib.sites',     # allauth 필수
    'allauth',                  # 회원가입
    'allauth.account',
    'allauth.socialaccount',    # 소셜 로그인용 (나중에 사용)
    'dj_rest_auth.registration', # 회원가입 API
    'corsheaders',               # CORS 허용
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'allauth.account.middleware.AccountMiddleware', # 미들웨어 (없으면 에러)
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'voxie_db',       # 서버에 만든 방 이름
        'USER': 'voxie_user',     # 서버 접속 ID
        'PASSWORD': '830d4e0fcf79a31051674d343ee7583ff004f148b53fb3bb46a28b60f6a8503e',       # 서버 접속 비번
        'HOST': '210.114.22.108',   # (Cafe24 서버의 "공인 IP")
        'PORT': '5432',           # 포트 번호
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# 2. DRF 설정: "기본 인증 수단으로 JWT를 쓰겠다" 선언
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'dj_rest_auth.jwt_auth.JWTCookieAuthentication', # JWT 쿠키 인증
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated', # 기본적으로 로그인해야 접근 가능
    ),
}

# 3. dj-rest-auth 설정 (JWT 활성화)
REST_AUTH = {
    'USE_JWT': True,                  # ★ 핵심: JWT 사용 켜기
    'JWT_AUTH_COOKIE': 'voxie-auth',  # 쿠키 이름 설정
    'JWT_AUTH_REFRESH_COOKIE': 'voxie-refresh',
}

# 4. Simple JWT 세부 설정 (유효기간 등)
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),  # 액세스 토큰 30분 유효
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),     # 재발급 토큰 7일 유효
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
}

# 5. 사이트 ID (Allauth 필수 설정)
SITE_ID = 1

# 2. 로그인 방식 (이메일 말고 ID로 로그인)
ACCOUNT_AUTHENTICATION_METHOD = 'username' 
ACCOUNT_EMAIL_REQUIRED = True            # 가입할 때 이메일 
ACCOUNT_UNIQUE_EMAIL = True              # 이메일 중복 금지
ACCOUNT_USERNAME_REQUIRED = True         # ID(닉네임) 

# 3. 이메일 인증 끄기 (개발용) ★ 이거 없으면 가입할 때 500 에러 터짐
ACCOUNT_EMAIL_VERIFICATION = 'none'

# CORS 설정 (프론트엔드 개발 서버 허용)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]
CORS_ALLOW_CREDENTIALS = True

# 4. JWT 설정
REST_USE_JWT = True
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60), # 토큰 1시간 유효
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),    # 재발급 7일
}